Create endpoints to check service status
tiagostutz/demo-warehouse-software pull request #26
Opened 2021-11-12 17:41 UTC by nabanitadewan

Created endpoints which query count of rows in product and article tables to check if the service is running or not.

This is my first time contributing to OSS , would love to hear your feedback . :)

2021-11-13 05:35 UTC, nabanitadewan commented
@tiagostutz please review my PR.

2021-11-13 10:10 UTC, tiagostutz commented
Hi @nabanitadewan !! Nice to receive your PR, good job!
I did the review and asked for some changes. If you have any doubts, please let me know. 🤓

2021-11-13 13:20 UTC, nabanitadewan commented
Hi @tiagostutz , I don't see changes requested.

2021-11-15 21:23 UTC, tiagostutz commented
Click on the `Files changed` tab and scroll down over the codes and check that there are inline changing requests, like this:

<img width="1429" alt="Screen Shot 2021-11-15 at 22 22 49" src="https://user-images.githubusercontent.com/3986989/141855694-77e30c55-ef61-451f-8af0-97c7e891fcec.png">

2021-11-16 19:00 UTC, nabanitadewan commented
@tiagostutz I am not sure if this is because of rights issue, but I still can't see change requests. So taking the screenshot as reference, I have changed Http status code to 200. Could you also paste other change request's screenshot?
![image](https://user-images.githubusercontent.com/18545426/142048656-5a35487e-7aee-4f09-a8d8-cff9d996668a.png)

2021-11-17 17:37 UTC, tiagostutz requested changes

2021-11-17 17:37 UTC, tiagostutz commented on api-backend/src/routes/article.ts
> +        res.status(201).send("ok");
Change status to 200. The "OK" status is 200.
Check this https://httpstatuses.com

2021-11-17 17:37 UTC, tiagostutz commented on api-backend/src/routes/article.ts
> +        res.status(404).send('Degraded');
If there was an error, the status should be 5xx. As this is an unexpected error, use 500 as status.

2021-11-17 17:37 UTC, tiagostutz commented on api-backend/src/routes/product.ts
> +        res.status(201).send("ok");
200 as status

2021-11-17 17:37 UTC, tiagostutz commented on api-backend/src/routes/product.ts
> +        res.status(404).send('Degraded');
500 as status

2021-11-17 17:37 UTC, tiagostutz commented on api-backend/src/services/article/tests/article.test.ts
> +    expect(result).not.toBeNull();
Add one more assert, verify that the status code should be equal to 200

2021-11-17 17:37 UTC, tiagostutz commented on api-backend/src/services/product/tests/product.test.ts
> +    expect(result).not.toBeNull();
Add assert on the status

2021-11-17 17:38 UTC, tiagostutz commented
@nabanitadewan my bad, I had forgot to push "Submit review". Now it should be visible to you 😄

2021-11-20 20:35 UTC, nabanitadewan commented
@tiagostutz . I have made the changes as requested. Could you please review it?

2021-11-25 17:41 UTC, tiagostutz approved these changes

2021-11-25 17:42 UTC, tiagostutz commented
Great job @nabanitadewan ! Thanks a lot for your contribution on this. 🥇

2021-11-25 17:42 UTC, merged